config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: "teams#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams, only: [:index,:show]  do
    collection do
      get 'search'
    end
  end

  resources :documents, only: [:index] 
  resources :users, only: [:index] 
  resources :a_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :b_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :c_tasks, only: [:index,:show,:new,:create,:edit,:update] 

end

app/models/a_certification.rb
class ACertification < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '実施中' }, { id: 3, name: 'A認定取得済' }
  ]

  include ActiveHash::Associations
  has_many :a_tasks
end

app/models/a_task.rb
class ATask < ApplicationRecord
  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100,
                               message: '0~100の値で入力して下さい' } do
    validates :operation_handover_material
    validates :incident_handover_material
    validates :failure_flow
  end

  with_options presence: true do
    validates :a_certification_id
    validates :user_id, uniqueness: true
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :a_certification
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/b_certification.rb
class BCertification < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '実施中' }, { id: 3, name: 'B認定取得済' }
  ]

  include ActiveHash::Associations
  has_many :b_tasks
end

app/models/b_task.rb
class BTask < ApplicationRecord
  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100,
                               message: '0~100の値で入力して下さい' } do
    validates :job_start
    validates :sending_media
    validates :status_change
    validates :alarm_support
    validates :failure_contact
  end

  with_options presence: true do
    validates :b_certification_id
    validates :user_id, uniqueness: true
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :b_certification
end

app/models/c_certification.rb
class CCertification < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '実施中' }, { id: 3, name: 'C認定取得済' }
  ]

  include ActiveHash::Associations
  has_many :c_tasks
end

app/models/c_task.rb
class CTask < ApplicationRecord
  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100,
                               message: '0~100の値で入力して下さい' } do
    validates :card_lending
    validates :get_log
    validates :surveillance_monitor
    validates :check_the_log
    validates :job_confirmation
  end

  with_options presence: true do
    validates :c_certification_id
    validates :user_id, uniqueness: true
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :c_certification
end

app/models/group.rb
class Group < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: 'Aグループ' }, { id: 3, name: 'Bグループ' },
    { id: 4, name: 'Cグループ' }, { id: 5, name: 'Dグループ' }
  ]

  include ActiveHash::Associations
  belongs_to :user
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_one :a_task
  has_one :b_task
  has_one :c_task

  with_options presence: true do
    validates :name
    validates :image
    validates :birthday
    validates :assignment_date
    validates :group_id
    validates :prefecture_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :group
end

app/controllers/a_tasks_controller.rb
class ATasksController < ApplicationController
  before_action :move_to_signed_in, only: [:edit, :new]
  before_action :set_a_task, only: [:show, :edit, :update]

  def index
    @a_task = ATask.includes(:user)
    @a_tasks = ATask.where(user_id: current_user.id) if user_signed_in?
  end

  def show
  end

  def edit
    redirect_to root_path unless @a_task.user_id == current_user.id
  end

  def new
    @a_task = ATask.new
  end

  def update
    if @a_task.update(a_task_params)
      redirect_to a_task_path(@a_task.id)
    else
      render :edit
    end
  end

  def create
    @a_task = ATask.new(a_task_params)
    if @a_task.save
      redirect_to a_task_path(@a_task.id)
    else
      render :new
    end
  end

  private

  def a_task_params
    params.require(:a_task).permit(:operation_handover_material, :incident_handover_material, :failure_flow,
                                   :a_certification_id).merge(user_id: current_user.id)
  end

  def move_to_signed_in
    redirect_to user_session_path unless user_signed_in?
  end

  def set_a_task
    @a_task = ATask.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(' ')
    end
    @q = User.ransack(params[:q])
    @teams = @q.result
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/helpers/a_tasks_helper.rb
module ATasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/b_tasks_helper.rb
module BTasksHelper
end

app/helpers/c_tasks_helper.rb
module CTasksHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class="error-message">
    <%= message %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamProfile</title>
    <html lang="ja">
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
        
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


</head>

  <body>
    <%= yield %>
    
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
              <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022
                            </div>
                        </div>
                    </div>
                </footer>
            </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

app/views/shared/_header-sidebar.html.erb
            <div id="layoutSidenav_content">
                <main>
       <div class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <%= link_to("Team Profilers", root_path, {class: "navbar-brand ps-3"}) %>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0 " id="sidebarToggle" href="#!"><div class=" btn btn-dark">Menu・Show / Hide</div></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    
                </div>
            </form>
            <!-- Navbar-->
      
        </nav>
       <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">メニュー</div>  
                             <%= link_to("運用メンバ一覧", root_path, {class: "nav-link"}) %>  
                             <%= link_to("メンバ情報一覧表", users_path, {class: "nav-link"}) %>  
                             <% if user_signed_in? %>
                            <%= link_to("マイプロフィール", team_path(current_user.id), {class: "nav-link"}) %>
                            <% end %>

                            <div class="sb-sidenav-menu-heading">教育目標</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                認定制度
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="pagesCollapseAuth"" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                     <%= link_to("A認定一覧", a_tasks_path, {class: "nav-link"}) %> 
                                     <%= link_to("B認定一覧", b_tasks_path, {class: "nav-link"}) %> 
                                     <%= link_to("C認定一覧", c_tasks_path, {class: "nav-link"}) %> 
                                </nav>
                            </div>
                    <%= link_to("認定項目手順書一覧", documents_path, {class: "nav-link"}) %>  

                        <div class="sb-sidenav-menu-heading">アカウント</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                アカウントメニュー
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                        <% unless user_signed_in?%>
                        <%= link_to("New account", new_user_registration_path, {class: 'nav-link'}) %>
                        <%= link_to("Login", new_user_session_path, {class: 'nav-link'}) %>
                        <% else %>
                        <%= link_to("Edit account", edit_user_registration_path, {class: 'nav-link'}) %>
                        <%= link_to('Logout', destroy_user_session_path, {method: :delete, class: 'nav-link'}) %>
                        <% end %>
                                </nav>
                            </div>


                        


                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Team Profilers
                    </div>

                </nav>
            </div>

     

app/views/tasks/show.html.erb
 <head>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.default.min.css">
<style>
#fav-table th {
    background-color:pink;
}

.sorter-false {
    background-image: none;
}
</style>
<script>
$(document).ready(function() {
    $('#fav-table').tablesorter({
            headers: {
               0: { sorter: false }
            }
    });
});
</script>
</head>
 
 <div class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <%= link_to("Team Profilers", root_path, {class: "navbar-brand ps-3"}) %>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">                     
                        <li><%= link_to("New account", new_user_registration_path, {class: 'btn dropdown-item'}) %></li>
                        <li><%= link_to("Edit account", edit_user_registration_path, {class: 'btn dropdown-item'}) %></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><%= link_to('Logout', destroy_user_session_path, {method: :delete, class: 'btn dropdown-item'}) %>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">メニュー</div>
                            <a class="nav-link" href="/">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                運用メンバ一覧
                            </a>
                            <div class="sb-sidenav-menu-heading">Interface</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                メンバーリスト
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="#">自社メンバ一覧</a>
                                    <a class="nav-link" href="#">マイプロフィール</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                教育目標
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        認定制度
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="#">A認定</a>
                                            <a class="nav-link" href="#">B認定</a>
                                            <%= link_to("C認定", tasks_path, {class: "nav-link"}) %>
                                            <a class="nav-link" href="#">C認定</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="charts.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Charts
                            </a>
                            <a class="nav-link" href="tables.html">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Tables
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <% if user_signed_in? %>
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                         <% else %>
                         <li><%= link_to("Click here to log in", new_user_session_path, {class: "breadcrumb-item active"}) %></li>
                         <% end %>
                        </ol>
                   
          
                    <div class="container">
                     <div class="row">

               <div class="card-body">
    <caption>メンバ一覧</caption>
    <table id="fav-table" class="table table-bordered">
  <thead>
      <tr><th>名前</th><th>年齢</th></tr>
  </thead>
  <tbody>
  <% @user.each do |user| %>
      <tr><td><%= user.name %></td><td><%= user.birthday %></td></tr>
      <% end %>
  </tbody>
</table>
</div>
                      
                       <%# <div class="col-12 ">
                      
                    <div class="input-group">
   <input type="text" class="form-control" placeholder="パスワード">
   <div class="input-group-append">
      <a href="#" class="btn btn-outline-success">Help</a>
      <a href="#" class="btn btn-outline-danger">忘れた</a>
   </div>
</div>

</div> %>
</div>
</div>

                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
      