config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: "teams#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams, only: [:index,:show]  do
    collection do
      get 'search'
    end
  end

  resources :documents, only: [:index] 
  resources :users, only: [:index] 
  resources :a_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :b_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :c_tasks, only: [:index,:show,:new,:create,:edit,:update] 

end

app/models/a_task.rb
class ATask < ApplicationRecord
  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100,
                               message: '0~100の値で入力して下さい' } do
    validates :operation_handover_material
    validates :incident_handover_material
    validates :failure_flow
  end

  with_options presence: true do
    validates :a_certification_id
    validates :user_id, uniqueness: true
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :a_certification
end

app/controllers/a_tasks_controller.rb
class ATasksController < ApplicationController
  before_action :move_to_signed_in, only: [:edit, :new]
  before_action :set_a_task, only: [:show, :edit, :update]

  def index
    @a_task = ATask.includes(:user)
    @a_tasks = ATask.where(user_id: current_user.id) if user_signed_in?
  end

  def show
  end

  def edit
    redirect_to root_path unless @a_task.user_id == current_user.id
  end

  def new
    @a_task = ATask.new
  end

  def update
    if @a_task.update(a_task_params)
      redirect_to a_task_path(@a_task.id)
    else
      render :edit
    end
  end

  def create
    @a_task = ATask.new(a_task_params)
    if @a_task.save
      redirect_to a_task_path(@a_task.id)
    else
      render :new
    end
  end

  private

  def a_task_params
    params.require(:a_task).permit(:operation_handover_material, :incident_handover_material, :failure_flow,
                                   :a_certification_id).merge(user_id: current_user.id)
  end

  def move_to_signed_in
    redirect_to user_session_path unless user_signed_in?
  end

  def set_a_task
    @a_task = ATask.find(params[:id])
  end
end

app/helpers/a_tasks_helper.rb
module ATasksHelper
end

app/views/a_tasks/edit.html.erb
<%= render "shared/header-sidebar" %>


            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>                     
                        </ol>

                        <div class="p-3 mb-2 bg-dark text-white"><%= "#{current_user.name}さんのA認定一覧 *自己評価0~100で入力 全項目が70以上でA認定取得" %> <br> 
                        該当作業実施・手順書閲覧後に自己評価を記入してください<br>
                        自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)
                        *50~70(手順に不明点がなく、二人作業の作業者であればできる)
                        *70~100(作業の手順・内容を理解しており二人作業での確認者ができる)<br>
                        <%= link_to('詳細ページへ', a_task_path(@a_task.id), {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %>
                        <%= link_to("一覧画面へ戻る", a_tasks_path, {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %> </div>
 
 <div class="container">
     <div class="row">
      <div class="col-12 mb-3 ">
  
     <div class="card-body">
    <table id="fav-table" class="table table-bordered">
  <thead>
      <tr>
      <th>名前</th>
      <th>A認定取得</th>  
       <th>オペレーション引き継ぎ資料の作成</th>
   <th>インシデント引き継ぎ資料の作成</th>
   <th>大規模故障発生時の対応フロー</th>
  </thead>
  <tbody>
  
      <tr>
      <td><%= @a_task.user.name %></td>
      <td><%= @a_task.a_certification.name %></td>
      <td><%= @a_task.operation_handover_material %></td>
    <td><%= @a_task.incident_handover_material %></td>
    <td><%= @a_task.failure_flow %></td>
      </tr>
   
  </tbody>
</table>
</div>
</div>
</div>
</div>
                   
<%= form_with model: @a_task, local: true do |f| %>
<%= render 'layouts/error_messages', model:f.object %>
 
        <div class="container">
     <div class="row">
      <div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">オペレーション引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :operation_handover_material, class:"input-default", id:"self_assessment", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass'></div>
  </div>
  </div>
  </div>
</div>
</div>


<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">インシデント引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :incident_handover_material, class:"input-default", id:"self_assessment_2", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_2'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">大規模故障発生時の対応フロー</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :failure_flow, class:"input-default", id:"self_assessment_3", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_3'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mt-3">
<label for="inputName">A認定</label>
      <div class="same-width-list mb-3 mb-md-0 d-flex ">
  <%= f.collection_select(:a_certification_id, ACertification.all, :id, :name, {}, {class:"select-box", id:"a_certification"}) %>
  </div>
  </div>


        <div class="a_passed mt-3" id='a_passed'>
        </div>

<%= f.submit "編集完了" ,class:"register-blue-btn mb-3" %>
<% end %>



</div>
</div>


                      
                

</main>
<%= render "shared/footer" %>
      </div>
      </div>

app/views/a_tasks/index.html.erb
 <head>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.default.min.css">
<style>
#fav-table th {
    background-color:#EEEEEE;
}

.sorter-false {
    background-image: none;
}

</style>
<script>
$(document).ready(function() {
    $('#fav-table').tablesorter({
  
    });
});
</script>
</head>

 
<%= render "shared/header-sidebar" %>

            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <% if user_signed_in? %>
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                         <% else %>
                         <li><%= link_to("Click here to log in", new_user_session_path, {class: "breadcrumb-item active"}) %></li>
                         <% end %>
                        </ol>


                        <div class="p-3 mb-2 bg-dark text-white">A認定一覧　*項目一覧へ自己評価0~100で入力 全項目が70以上でA認定取得<br>
                        該当作業実施・手順書閲覧後に自己評価を記入してください<br>
                        自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)
                        *50~70(手順に不明点がなく、二人作業の作業者であればできる)
                        *70~100(作業の手順・内容を理解しており二人作業での確認者ができる)
                        </div>
 
<div class="row d-flex">
                                    <div class="col-6">
                                <div class="card bg-primary mb-3">
                                  
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('B認定一覧はこちら', b_tasks_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>

                             <div class="col-6">
                                <div class="card bg-warning mb-3">
                                  
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('C認定一覧はこちら', c_tasks_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            </div>

       <div class="container">
                     <div class="row d-flex">
                     <% if user_signed_in?%>
                      <% @a_tasks.each do |a_task| %>

                         <div class="col-lg-2 col-4 mb-3 ">
                        <div class="card mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag a_task.user.image,  class: "img-fluid"%></div>
                                                        <div class="card-body">
                               
                                 <%= link_to('A認定詳細', a_task_path(a_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>

                                 <%= link_to('編集', edit_a_task_path(a_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>
                                 
                                </div>
                                </div>
                            </div>
                       
                      <div class="col-md-9">
       <div class="card border-light mb-3">
          

            <div class="card-header">マイプロフィール</div>
            <div class="card-body">
            <h6 class="breadcrumb-item active">氏名</h6>
            
              <p class="card-text"><%= a_task.user.name %></p>

              <h6 class="breadcrumb-item active">A認定</h6>
              <% if a_task.user.present? %>
              <p class="card-text"><%= a_task.a_certification.name %></p>
              <% elsif %>
              <%= "---" %>
              <% end %>

            </div>
          </div>
          </div>
           <tbody>
  <table class="mytable mb-3">

    <h5><%= "#{a_task.user.name}さんのA認定項目一覧" %></h5>
   <th>オペレーション引き継ぎ資料の作成</th>
   <th>インシデント引き継ぎ資料の作成</th>
   <th>大規模故障故障発生時の対応フロー</th>

  </tr>
  <tr>
 
    <td><%= a_task.operation_handover_material %></td>
    <td><%= a_task.incident_handover_material %></td>
    <td><%= a_task.failure_flow %></td>
 
  </tr>
</table>
</tbody>
 <% end %>



                                           
              <% unless @a_tasks.present? %>
                            <div class="col-12">
                                <div class="card bg-danger text-white mb-4 ">
                                    <div class="card-body">A認定新規登録画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('こちらをクリックし新規登録をお願いします', new_a_task_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                 <% end %>

                        </div>

                </div>
<% end %>

<% unless user_signed_in? %>
<div class="row">
                            <div class="col-xl-6 col-md-6">
                                       <div class="card bg-danger text-white mb-4 mt-3">
                                    <div class="card-body">ユーザログイン画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('ログイン後、A認定登録をお願いします', new_user_session_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
   
                            <div class="col-xl-6 col-md-6">
                                <div class="card bg-success text-white mb-4 mt-3">
                             <div class="card-body">ユーザ新規登録画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('アカウント登録がまだの方は、こちらから新規登録をお願いします', new_user_registration_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>

                        </div>
<% end %>



<div class="p-3 mb-2 bg-dark text-white">A認定実施メンバ一覧 </div>
                        <div class="card-body">
    <table id="fav-table" class="table table-bordered">
  <thead>
      <tr>
      <th>名前</th>
      <th>所属グループ</th>
      <th>A認定取得</th>
    <th>オペレーション引き継ぎ資料の作成</th>
    <th>インシデント引き継ぎ資料の作成</th>
    <th>大規模故障発生時の対応フロー</th>

      </tr>
  </thead>
  <tbody>
  <% @a_task.each do |a_task| %>
      <tr><td><%= a_task.user.name %></td>
      <td><%= a_task.user.group.name %></td>
      <td><%= a_task.a_certification.name %></td>
      <td><%= a_task.operation_handover_material %></td>
    <td><%= a_task.incident_handover_material %></td>
    <td><%= a_task.failure_flow %></td>
      <% end %>
  </tbody>
</table>
</div>

                <div class="container">
                     <div class="row">
                      <% @a_task.each do |a_task| %>
                       <div class="col-lg-2 col-4 mb-3 ">
                        <div class="card h-100 mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag a_task.user.image, class: "img-fluid"%></div>
                            <div class="card-body">
                                <h5 class="card-text text-truncate"><%= a_task.user.name %></h5>
                                <p class="card-text text-truncate">
                                <%= a_task.user.group.name %>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                 <%= link_to( 'A認定詳細', a_task_path(a_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>
                                 
                                </div>
                                </div>
                            </div>
                        </div>
                      </div>
                    <% end %>
                



 
 </div>
</div>
</div>



                </main>
                <%= render "shared/footer" %>

        </div>
    </div>
   
      

app/views/a_tasks/new.html.erb
<%= render "shared/header-sidebar" %>

  <div id="layoutSidenav_content">
                <main>

                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                        </ol>
                        

                        <div class="p-3 mb-2 bg-dark text-white ">A認定教育項目一覧*自己評価0~100で入力 全項目が70以上でA認定取得 <br>  
                        該当作業実施・手順書閲覧後に自己評価を記入してください<br>
                        自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)
                        *50~70(手順に不明点がなく、二人作業の作業者であればできる)
                        *70~100(作業の手順・内容を理解しており二人作業での確認者ができる)
                        </div>
                       

                   
                        <%= form_with model: @a_task, local: true do |f| %>
<%= render 'layouts/error_messages', model:f.object %>
    <div class="container">
     <div class="row">
      <div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body mt-3">
   <div class="aaa">
    <h5 class="card-title">オペレーション引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :operation_handover_material, class:"input-default", id:"self_assessment", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass'></div>
  </div>
  </div>
  </div>
</div>
</div>


<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">インシデント引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :incident_handover_material, class:"input-default", id:"self_assessment_2", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_2'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">大規模故障発生時の対応フロー</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :failure_flow, class:"input-default", id:"self_assessment_3", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_3'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mt-3">
<label for="inputName">A認定</label>
      <div class="same-width-list mb-3 mb-md-0 d-flex ">
  <%= f.collection_select(:a_certification_id, ACertification.all, :id, :name, {}, {class:"select-box", id:"a_certification"}) %>
  </div>
  </div>


        <div class="a_passed mt-3" id='a_passed'>
        </div>



<%= f.submit "新規登録完了" ,class:"register-blue-btn mt-5 mb-5" %>
<% end %>



</div>
</div>



</div>  
    







<%= render "shared/footer" %>
      
      </div>   

app/views/a_tasks/show.html.erb
<%= render "shared/header-sidebar" %>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <% if user_signed_in? %>
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                         <% else %>
                         <li><%= link_to("Click here to log in", new_user_session_path, {class: "breadcrumb-item active"}) %></li>
                         <% end %>
                        </ol>

                       
                        <div class="p-3 mb-2 bg-dark text-white "><%= "#{@a_task.user.name}さんのA認定教育項目一覧*自己評価0~100で入力 全項目が70以上でA認定取得" %><br> 
                        該当作業実施・手順書閲覧後に自己評価を記入してください<br>
                        自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)
                        *50~70(手順に不明点がなく、二人作業の作業者であればできる)
                        *70~100(作業の手順・内容を理解しており二人作業での確認者ができる)<br>
                        <% if user_signed_in? %>
                         <% if  current_user.id == @a_task.user_id %>
                        <%= link_to('A認定編集', edit_a_task_path(@a_task.id), {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %>
                        <% end %>
                        <% end %>
                        <%= link_to("一覧画面へ戻る", a_tasks_path, {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %> 
                        <br>
                        </div>
                       

                         <% if @a_task.a_certification_id == 3 %> 
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
       <%= image_tag 'a_icon.png',class:"img-fluid" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @a_task.user.name %>様　A認定取得</h5>
        <p class="card-text"><br>A認定取得おめでとうございます！次はS認定取得に向けて取り組んでいきましょう！
        </p>
        
      </div>
    </div>
  </div>
</div>
                            <% end %>
                        

    
    <div class="container">
     <div class="row">
      

 <tbody>
  <div class="col-2 mb-3 ">
                        <div class="card mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag @a_task.user.image,  class: "img-fluid"%>
                            </div>
                            </div>
                            </div>

<div class="col-10 mb-3 ">
  <table class="mytable mb-3">

     <tr>
      <th>名前</th>
      <th>所属グループ</th>
      <th>A認定取得</th>
    <th>オペレーション引き継ぎ資料の作成</th>
    <th>インシデント引き継ぎ資料の作成</th>
    <th>大規模故障故障発生時の対応フロー</th>
      </tr>
      <tr><td><%= @a_task.user.name %></td>
      <td><%= @a_task.user.group.name %></td>
      <td><%= @a_task.a_certification.name %></td>
      <td><%= @a_task.operation_handover_material %></td>
    <td><%= @a_task.incident_handover_material %></td>
    <td><%= @a_task.failure_flow %></td>
  </tr>
</table>
</tbody>
</div>
</div>
      
      
<div class="card mb-3" >
<div class="col-10 d-flex">
  <div class="card-body">
   <div class="document"> 
    <h5 class="card-title">オペレーション引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="assessment ">
     <div class="col-12  mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment" ><%= @a_task.operation_handover_material %></div>
  </div>
  </div>
  </div>
</div>



<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">インシデント引き継ぎ資料の作成</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="assessment d-flex">
     <div class="col-sm-12mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment_2" ><%= @a_task.incident_handover_material %></div>
  </div>
 
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">大規模故障発生時の対応フロー</h5>
     <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

<div class="assessment d-flex">
     <div class="col-sm-12 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment_3" ><%=  @a_task.failure_flow %></div>
  </div>

  
  </div>
  </div>
</div>
</div>


<div class="col-md-12 mt-3 ">

</div>





</div>
</div>


</main>
<%= render "shared/footer" %>
      </div>