config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  root to: "teams#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teams, only: [:index,:show]  do
    collection do
      get 'search'
    end
  end

  resources :documents, only: [:index] 
  resources :users, only: [:index] 
  resources :a_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :b_tasks, only: [:index,:show,:new,:create,:edit,:update]
  resources :c_tasks, only: [:index,:show,:new,:create,:edit,:update] 

end

app/models/c_task.rb
class CTask < ApplicationRecord
  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100,
                               message: '0~100の値で入力して下さい' } do
    validates :card_lending
    validates :get_log
    validates :surveillance_monitor
    validates :check_the_log
    validates :job_confirmation
  end

  with_options presence: true do
    validates :c_certification_id
    validates :user_id, uniqueness: true
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :c_certification
end

app/controllers/c_tasks_controller.rb
class CTasksController < ApplicationController
  before_action :move_to_signed_in, only: [:edit, :new]
  before_action :set_c_task, only: [:show, :edit, :update]

  def index
    @c_task = CTask.includes(:user)
    @c_tasks = CTask.where(user_id: current_user.id) if user_signed_in?
  end

  def show
  end

  def edit
    redirect_to root_path unless @c_task.user_id == current_user.id
  end

  def new
    @c_task = CTask.new
  end

  def update
    if @c_task.update(c_task_params)
      redirect_to c_task_path(@c_task.id)
    else
      render :edit
    end
  end

  def create
    @c_task = CTask.new(c_task_params)
    if @c_task.save
      redirect_to c_task_path(@c_task.id)
    else
      render :new
    end
  end

  private

  def c_task_params
    params.require(:c_task).permit(:card_lending, :get_log, :surveillance_monitor, :check_the_log,
                                   :job_confirmation, :c_certification_id).merge(user_id: current_user.id)
  end

  def move_to_signed_in
    redirect_to user_session_path unless user_signed_in?
  end

  def set_c_task
    @c_task = CTask.find(params[:id])
  end
end

app/helpers/c_tasks_helper.rb
module CTasksHelper
end

app/views/c_tasks/edit.html.erb
<%= render "shared/header-sidebar" %>


            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>                     
                        </ol>

                        <div class="p-3 mb-2 bg-dark text-white"><%= "#{current_user.name}さんのC認定一覧　*自己評価0~100で入力 全項目が70以上でC認定取得" %> <br> 
                        <%= "該当作業実施・手順書閲覧後に自己評価を記入してください" %><br>
                        <%="自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)" %>
                        <%= "*50~70(手順に不明点がなく、二人作業の作業者であればできる)" %>
                        <%= "*70~100(作業の手順・内容を理解しており二人作業での確認者ができる)" %><br>


                        <%= link_to('詳細ページへ', c_task_path(@c_task.id), {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %>
                        <%= link_to("一覧画面へ戻る", c_tasks_path, {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %> </div>
 
 <div class="container">
     <div class="row">
      <div class="col-12 mb-3 ">
  
     <div class="card-body">
    <table id="fav-table" class="table table-bordered">
  <thead>
      <tr><th>名前</th><th>C認定取得</th><th>定時起動JOBの確認</th><th>監視ログ定点確認</th><th>監視画面の正常性確認</th><th>業務ログ取得</th><th>セキュリティカードの貸出</th></tr>
  </thead>
  <tbody>
  
      <tr>
      <td><%= @c_task.user.name %></td>
      <td><%= @c_task.c_certification.name %></td>
      <td><%= @c_task.job_confirmation %></td>
      <td><%= @c_task.check_the_log %></td>
      <td><%= @c_task.surveillance_monitor %></td>
      <td><%= @c_task.get_log %></td>
      <td><%= @c_task.card_lending %></td>
      </tr>
   
  </tbody>
</table>
</div>
</div>
</div>
</div>
                   
<%= form_with model: @c_task, local: true do |f| %>
<%= render 'layouts/error_messages', model:f.object %>
 
    <div class="container">
     <div class="row">
      <div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">定時起動ジョブの確認</h5>
       <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :job_confirmation, class:"input-default", id:"self_assessment", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass'></div>
  </div>
  </div>
  </div>
</div>
</div>


<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">定例業務ログ取得</h5>
       <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :get_log, class:"input-default", id:"self_assessment_2", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_2'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">監視画面の正常性確認</h5>
      <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :surveillance_monitor, class:"input-default", id:"self_assessment_3", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_3'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">監視ログ定点確認</h5>
      <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :check_the_log, class:"input-default", id:"self_assessment_4", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_4'></div>
  </div>
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-12 mb-3 d-flex">
  <div class="card-body">
   <div class="aaa">
    <h5 class="card-title">セキュリティカードの貸出</h5>
        <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-6 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <%= f.text_area :card_lending, class:"input-default", id:"self_assessment_5", placeholder:"半角数字で入力してください",maxlength:"3" %>
  </div>
   <div class="col-sm-2 mt-2 ms-4">
      <div class="pass-content">
          <span>判定</span>
        </div>
        <div class="pass" id='pass_5'></div>
 
  
</div>
</div>
</div>
</div>


<div class="col-12 mt-3">
<label for="inputName">C認定</label>
      <div class="same-width-list mb-3 mb-md-0 d-flex ">
  <%= f.collection_select(:c_certification_id, CCertification.all, :id, :name, {}, {class:"select-box", id:"c_certification"}) %>
  </div>
  </div>


        <div class="c_passed mt-3" id='c_passed'>
        </div>

<%= f.submit "編集完了" ,class:"register-blue-btn mt-3" %>
<% end %>



</div>
</div>
</div>
</div>
                      
                

</main>
<%= render "shared/footer" %>
      

app/views/c_tasks/index.html.erb
 <head>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/js/jquery.tablesorter.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.0/css/theme.default.min.css">
<style>
#fav-table th {
    background-color:#EEEEEE;
}

.sorter-false {
    background-image: none;
}

</style>
<script>
$(document).ready(function() {
    $('#fav-table').tablesorter({
  
    });
});
</script>
</head>

 
<%= render "shared/header-sidebar" %>

            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <% if user_signed_in? %>
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                         <% else %>
                         <li><%= link_to("Click here to log in", new_user_session_path, {class: "breadcrumb-item active"}) %></li>
                         <% end %>
                        </ol>


                        <div class="p-3 mb-2 bg-dark text-white">C認定一覧　*項目一覧へ自己評価0~100で入力 全項目が70以上でC認定取得
                         <br> 
                        <%= "該当作業実施・手順書閲覧後に自己評価を記入してください" %><br>
                        <%="自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)" %>
                        <%= "*50~70(手順に不明点がなく、二人作業の作業者であればできる)" %>
                        <%= "*70~100(作業の手順・内容を理解しており二人作業での確認者ができる)" %><br>
                        </div>

                                                    <div class="row d-flex">
                                    <div class="col-6">
                                <div class="card bg-danger mb-3">
                                  
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('A認定一覧はこちら', a_tasks_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>

                             <div class="col-6">
                                <div class="card bg-primary mb-3">
                                  
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('B認定一覧はこちら', b_tasks_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        

       <div class="container">
                     <div class="row d-flex">
                     <% if user_signed_in?%>
                      <% @c_tasks.each do |c_task| %>


                         <div class="col-lg-2 col-4 mb-3 ">
                        <div class="card mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag c_task.user.image,  class: "img-fluid"%></div>
                                                        <div class="card-body">
                               
                                 <%= link_to('C認定詳細', c_task_path(c_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>
                                 <%= link_to('編集', edit_c_task_path(c_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>
                                </div>
                                </div>
                            </div>
                       
                      <div class="col-md-9">
       <div class="card border-light mb-3">
          

            <div class="card-header">マイプロフィール</div>
            <div class="card-body">
            <h6 class="breadcrumb-item active">氏名</h6>
            
              <p class="card-text"><%= c_task.user.name %></p>

              <h6 class="breadcrumb-item active">C認定</h6>
              <% if c_task.user.present? %>
              <p class="card-text"><%= c_task.c_certification.name %></p>
              <% elsif %>
              <%= "---" %>
              <% end %>

            </div>
          </div>
          </div>
           <tbody>
  <table class="mytable mb-3">

    <h5><%= "#{c_task.user.name}さんのC認定項目一覧" %></h5>
   <th>定時起動JOBの確認</th>
   <th>監視ログ定点確認</th>
   <th>監視画面の正常性確認</th>
   <th>業務ログ取得</th>
   <th>セキュリティカードの貸出</th>
  </tr>
  <tr>
 
    <td><%= c_task.job_confirmation %></td>
    <td><%= c_task.check_the_log %></td>
    <td><%= c_task.surveillance_monitor %></td>
    <td><%= c_task.get_log %></td>
    <td><%= c_task.card_lending %></td>
  </tr>
</table>
</tbody>
 <% end %>



                                           
              <% unless @c_tasks.present? %>
                            <div class="col-12">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">C認定新規登録画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('こちらをクリックし新規登録をお願いします', new_c_task_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                 <% end %>

                        </div>

                </div>
<% end %>

<% unless user_signed_in? %>

<div class="container">
                         <div class="row">
                            <div class="col-xl-6 col-md-6">
                                       <div class="card bg-warning text-white mb-4 mt-3">
                                    <div class="card-body">ユーザログイン画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('ログイン後、C認定登録をお願いします', new_user_session_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
   
                            <div class="col-xl-6 col-md-6">
                                <div class="card bg-success text-white mb-4 mt-3">
                             <div class="card-body">ユーザ新規登録画面</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                    <%= link_to('アカウント登録がまだの方は、こちらから新規登録をお願いします', new_user_registration_path, {class: "small text-white stretched-link"}) %>
                                        <div class="small text-black"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                     </div>
<% end %>



<div class="p-3 mb-2 bg-dark text-white">C認定実施メンバ一覧 </div>
                        <div class="card-body">
    <table id="fav-table" class="table table-bordered">
  <thead>
      <tr><th>名前</th><th>所属グループ</th><th>C認定取得</th><th>定時起動JOBの確認</th><th>監視ログ定点確認</th><th>監視画面の正常性確認</th><th>業務ログ取得</th><th>セキュリティカードの貸出</th></tr>
  </thead>
  <tbody>
  <% @c_task.each do |c_task| %>
      <tr><td><%= c_task.user.name %></td>
      <td><%= c_task.user.group.name %></td>
      <td><%= c_task.c_certification.name %></td>
      <td><%= c_task.job_confirmation %></td>
      <td><%= c_task.check_the_log %></td>
      <td><%= c_task.surveillance_monitor %></td>
      <td><%= c_task.get_log %></td>
      <td><%= c_task.card_lending %></td></tr>
      <% end %>
  </tbody>
</table>
</div>

                <div class="container">
                     <div class="row">
                      <% @c_task.each do |c_task| %>
                       <div class="col-lg-2 col-4 mb-3 ">
                        <div class="card h-100 mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag c_task.user.image, class: "img-fluid"%></div>
                            <div class="card-body">
                                <h5 class="card-text text-truncate"><%= c_task.user.name %></h5>
                                <p class="card-text text-truncate">
                                <%= c_task.user.group.name %>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                 <%= link_to( 'C認定詳細', c_task_path(c_task.id), {class: "btn btn-sm btn-outline-secondary"}) %>
                                 
                                </div>
                                </div>
                            </div>
                        </div>
                      </div>
                    <% end %>
                



 
 </div>
</div>
</div>



                </main>
                <%= render "shared/footer" %>

        </div>
    </div>
   
      

app/views/c_tasks/show.html.erb
<%= render "shared/header-sidebar" %>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">教育タスク一覧</h1>
                        <ol class="breadcrumb mb-4">
                         <% if user_signed_in? %>
                         <li class="breadcrumb-item active"><%= "#{current_user.name}さんがログイン中です" %></li>
                         <% else %>
                         <li><%= link_to("Click here to log in", new_user_session_path, {class: "breadcrumb-item active"}) %></li>
                         <% end %>
                        </ol>

                       
                        <div class="p-3 mb-2 bg-dark text-white "><%= "#{@c_task.user.name}さんのC認定教育項目一覧*自己評価0~100で入力 全項目が70以上でC認定取得" %><br> 
                        <%= "該当作業実施・手順書閲覧後に自己評価を記入してください" %><br>
                        <%="自己評価基準: *0~50(手順に不明点等があり一人称での作業が難しい)" %>
                        <%= "*50~70(手順に不明点がなく、二人作業の作業者であればできる)" %>
                        <%= "*70~100(作業の手順・内容を理解しており二人作業での確認者ができる)" %><br>
                        <% if user_signed_in? %>
                         <% if  current_user.id == @c_task.user_id %>
                        <%= link_to('C認定編集', edit_c_task_path(@c_task.id), {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %>
                        <% end %>
                        <% end %>
                        <%= link_to("一覧画面へ戻る", c_tasks_path, {class: "btn btn-sm btn-outline-secondary text-white mt-3 p-10"}) %> 
                        <br>
                        </div>
                       

                         <% if @c_task.c_certification_id == 3 %> 
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
       <%= image_tag 'c_icon.png',class:"img-fluid" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @c_task.user.name %>様　C認定取得</h5>
        <p class="card-text"><br>C認定取得おめでとうございます！次はB認定取得に向けて取り組んでいきましょう！
        </p>
        
      </div>
    </div>
  </div>
</div>
                            <% end %>
                        

    
    <div class="container">
     <div class="row">
      

 <tbody>
  <div class="col-2 mb-3 ">
                        <div class="card mb-6 shadow-sm">
                            <div class="bd-placeholder-img card-img-top ">
                            <%= image_tag @c_task.user.image,  class: "img-fluid"%>
                            </div>
                            </div>
                            </div>

<div class="col-10 mb-3 ">
  <table class="mytable mb-3">

    <th>名前</th>
    <th>C認定</th>
   <th>定時起動JOBの確認</th>
   <th>監視ログ定点確認</th>
   <th>監視画面の正常性確認</th>
   <th>業務ログ取得</th>
   <th>セキュリティカードの貸出</th>
  </tr>
  <tr>
    <td><%= @c_task.user.name %></td>
    <td><%= @c_task.c_certification.name %></td>
    <td><%= @c_task.job_confirmation %></td>
    <td><%= @c_task.check_the_log %></td>
    <td><%= @c_task.surveillance_monitor %></td>
    <td><%= @c_task.get_log %></td>
    <td><%= @c_task.card_lending %></td>
  </tr>
</table>
</tbody>
</div>
</div>
      
      
<div class="card mb-3" >
<div class="col-10 d-flex">
  <div class="card-body">
   <div class="document"> 
    <h5 class="card-title">定時起動ジョブの確認</h5>
    <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
    
 </div>
</div>

 <div class="assessment ">
     <div class="col-12  mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment" ><%= @c_task.job_confirmation %></div>
  </div>
  </div>
  </div>
</div>



<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">定例業務ログ取得</h5>
        <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="assessment d-flex">
     <div class="col-sm-12mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment_2" ><%= @c_task.get_log %></div>
  </div>
 
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">監視画面の正常性確認</h5>
       <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

<div class="assessment d-flex">
     <div class="col-sm-12 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment_3" ><%=  @c_task.surveillance_monitor %></div>
  </div>

  
  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">監視ログ定点確認</h5>
       <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

 <div class="bbb d-flex">
     <div class="col-sm-12 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
    <div class="input-default", id="self_assessment_4" ><%=  @c_task.check_the_log %></div>
  </div>

  </div>
  </div>
</div>
</div>

<div class="col-12 mb-3 ">
<div class="card" >
<div class="col-10 mb-3 d-flex">
  <div class="card-body">
   <div class="document">
    <h5 class="card-title">セキュリティカードの貸出</h5>
       <%= link_to('運用手順書 ***　手順書格納先 ***', documents_path, {class: "link-dark"}) %> 
 </div>
</div>

<div class="assessment d-flex">
     <div class="col-sm-12 mt-2">
    <label for="inputName">自己評価(0~100の評価で入力)</label>
      <div class="input-default", id="self_assessment_5" ><%=  @c_task.card_lending %></div>
  </div>

</div>


  
  </div>
</div>
<div class="col-md-12 mt-3 ">

</div>





</div>
</div>
</div>

</main>
<%= render "shared/footer" %>
      